app:
  # Python logging level: DEBUG | INFO | WARNING | ERROR
  log_level: "INFO"
  base_url: "https://solid-carnival-qxqxqwwjwgqf4qw7-80.app.github.dev"

  docs_folder: "/app/docs"
  research_folder: "/app/research"

mail:
  smtp_host: "smtp.protonmail.ch"
  smtp_port: 587
  smtp_use_tls: true
  smtp_user: "mutau@erikdonath.de"
  smtp_password: "LBJW882CC5RCH7EK"